name: "FinancialControlWEB"

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  K8S_NAMESPACE: financialcontrol
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout GithubActions
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push (Financial API)
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/financial_web:latest
            ${{ env.DOCKER_USERNAME }}/financial_web:v${{ github.run_number }}

  deploy:
    needs: [build]
    runs-on: ubuntu-20.04
    environment:
      name: deploy
    steps:
      - name: Checkout GithubActions
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}

      - name: Deploy Namespace
        uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            .k8s/namespaces/financialcontrol.yaml

      - name: Deploy (Financial Control WEB)
        uses: Azure/k8s-deploy@v1.3
        with:
          namespace: ${{ env.K8S_NAMESPACE }}
          images: ${{ env.DOCKER_USERNAME }}/financial_web:v${{ github.run_number }}
          manifests: |
            .k8s/deployments/financialweb-dp.yaml
            .k8s/services/financialweb-svc.yaml
            .k8s/certmanager/issuer.yaml
            .k8s/ingress/ingress.yaml
